import numpy as np
import matplotlib.pyplot as plt
n_epochs = np.arange(20,1000,50)
train_Adam_losses = np.load('./adam_loss.npy')
train_SGD_losses = np.load('./sdg_loss.npy')
SGD_times= np.load('./gpu/sdg_time.npy')
Adam_times= np.load('./gpu/adam_time.npy')
plt.figure()
plt.plot(n_epochs, train_Adam_losses)
plt.plot(n_epochs, Adam_times)
plt.plot(n_epochs, train_SGD_losses)
plt.plot(n_epochs, SGD_times)
plt.legend(["Adam: losses", "Adam:time", "SGD: losses", "SGD: times"])
plt.savefig('./partF_CPU.png')
train_Adam_losses = np.load('./gpu/adam_loss.npy')
train_SGD_losses = np.load('./gpu/sdg_loss.npy')
SGD_times= np.load('./sdg_time.npy')
Adam_times= np.load('./adam_time.npy')
plt.figure()
plt.plot(n_epochs, train_Adam_losses)
plt.plot(n_epochs, Adam_times)
plt.plot(n_epochs, train_SGD_losses)
plt.plot(n_epochs, SGD_times)
plt.legend(["Adam: losses", "Adam:time", "SGD: losses", "SGD: times"])
plt.savefig('./partF_GPU.png')
